image: python:3.13

before_script:
  - pip install poetry
  - poetry install --no-root

pages:
  stage: deploy
  script:
  - cd dpm-docs
  - poetry run mkdocs build --site-dir public
  artifacts:
    paths:
    - public
