site_name: DPM Expression Language (DPM-XL) Documentation
site_description: Comprehensive documentation for the Data Point Model Expression Language
site_author: DPM-XL Standards Committee
repo_url: https://gitlab.com/aollerosr/dpm-xl-docs
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - mermaid2:
      version: 11.8.0

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra_css:
  - style.css

nav:
  - Home: index.md
  - Information Model:
    - Introduction: information-model/introduction.md
    - Information Model: information-model/information-model.md
    - DPM-XL Data Selection: information-model/data-selection.md
    - Null handling: information-model/null-treatment.md
    - DPM-ML: information-model/dpm-ml.md


